---
- astyle:
    enabled: true
    include:
    - test/integration/astyle/**/*
- autopep8:
    enabled: true
    include:
    - test/integration/autopep8/**/*
- black:
    enabled: true
    include:
    - test/integration/black/**/*
- brittany:
    enabled: true
    include:
    - test/integration/brittany/**/*
- clang-format:
    enabled: true
    include:
    - test/integration/clang-format/**/*
- dfmt:
    enabled: true
    include:
    - test/integration/dfmt/**/*
- elm-format:
    enabled: true
    include:
    - test/integration/elm-format/**/*
- google-java-format:
    enabled: true
    include:
    - test/integration/google-java-format/**/*
- hindent:
    enabled: true
    include:
    - test/integration/hindent/**/*
- hlint:
    enabled: true
    include:
    - test/integration/hlint/**/*
- jdt:
    enabled: true
    include:
    - test/integration/jdt/**/*
- jq:
    enabled: true
    include:
    - test/integration/jq/**/*
- ormolu:
    enabled: true
    include:
    - test/integration/ormolu/**/*
- pg_format:
    enabled: true
    include:
    - test/integration/pg_format/**/*
- php-cs-fixer:
    enabled: true
    include:
    - test/integration/php-cs-fixer/**/*
- prettier-markdown:
    enabled: true
    include:
    - test/integration/prettier-markdown/**/*
- prettier-ruby:
    enabled: true
    include:
    - test/integration/prettier-ruby/**/*
- prettier-yaml:
    enabled: true
    include:
    - test/integration/prettier-yaml/**/*
- prettier:
    enabled: true
    include:
    - test/integration/prettier/**/*
- reorder-python-imports:
    enabled: true
    include:
    - test/integration/reorder-python-imports/**/*
- rubocop:
    enabled: true
    include:
    - test/integration/rubocop/**/*
- rustfmt:
    enabled: true
    include:
    - test/integration/rustfmt/**/*
- shellharden:
    enabled: true
    include:
    - test/integration/shellharden/**/*
- shfmt:
    enabled: true
    include:
    - test/integration/shfmt/**/*
- stylish-haskell:
    enabled: true
    include:
    - test/integration/stylish-haskell/**/*
- terraform:
    enabled: true
    include:
    - test/integration/terraform/**/*
- whitespace:
    enabled: true
    include:
    - test/integration/whitespace/**/*
- yapf:
    enabled: true
    include:
    - test/integration/yapf/**/*
